AWSTemplateFormatVersion: '2010-09-09'
Description: 'Child Task Definition and ECS Service for sample-service-__TYPE__ with rolling update deployment.'

# ─── Parameters ───────────────────────────────────────────────────────────────
Parameters:
  # ─────── General ───────
  ECSClusterName:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/ecs/ClusterName:1}}'
  Image:
    Type: String
  Environment:
    Type: String
    Default: stage
  TemplateBucketUrl:
    Type: String
    Default: https://rpx.cf.ecs.template.nonprod.s3.us-east-1.amazonaws.com/templates
  Namespace:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/servicediscovery/NamespaceArn:1}}'

  # ─────── Application ───────
  AppName:
    Type: String
    Default: sample-service-__TYPE__
  ContainerPort:
    Type: Number
    Default: 80
  TaskCPU:
    Type: Number
    Default: 512
  TaskMemory:
    Type: Number
    Default: 1024
  sample-serviceIAMRoleArn:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/iam/sample-service/TaskRoleArn:1}}'
  ExecutionRoleArn:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/ecs/TaskExecutionRoleArn:1}}'

  # ─────── Loadbalancer ───────
  ALBHTTPListenerArn:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/alb/HTTPListenerArn:1}}'
  AppHostHeader:
    Type: String
    Default: 'sample-service.stage.rpxcorp.com'
  ListenerRulePriority:
    Type: Number
    Default: 100

  # ─────── Networking ───────
  VpcId:
    Type: String
    Default: '{{resolve:ssm:/cfn/vpc/VpcId:1}}'
  PrivateSubnet1:
    Type: String
    Default: '{{resolve:ssm:/cfn/vpc/PrivateSubnet1:1}}'
  PrivateSubnet2:
    Type: String
    Default: '{{resolve:ssm:/cfn/vpc/PrivateSubnet2:1}}'
  SecurityGroupId:
    Type: String
    Default: '{{resolve:ssm:/cfn/stage/ecs/InstanceSecurityGroupId:1}}'

  # ─────── Scaling ───────
  DesiredCount:
    Type: Number
    Default: 1
  ScalingMinCapacity:
    Type: Number
    Default: 1
  ScalingMaxCapacity:
    Type: Number
    Default: 2
  CPUScaleOutThreshold:
    Type: Number
    Default: 80
  CPUScaleInThreshold:
    Type: Number
    Default: 40
  MemoryScaleOutThreshold:
    Type: Number
    Default: 80
  MemoryScaleInThreshold:
    Type: Number
    Default: 80

# ─── Resources ────────────────────────────────────────────────────────────────
Resources:        
  # ─────── Task Definition ───────────────
  __CF_APP_NAME____TYPE__TaskDefStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${TemplateBucketUrl}/task-definition.yaml'
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        Image: !Ref Image
        ContainerPort: !Ref ContainerPort
        TaskCPU: !Ref TaskCPU
        TaskMemory: !Ref TaskMemory
        TaskRoleArn: !Ref sample-serviceIAMRoleArn
        ExecutionRoleArn: !Ref ExecutionRoleArn

  # ─────── ECS Service ──────────────
  __CF_APP_NAME__ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: __CF_APP_NAME____TYPE__TaskDefStack
    Properties:
      TemplateURL: !Sub '${TemplateBucketUrl}/ecs-service-rolling-update.yaml'
      Parameters:
        Environment: !Ref Environment
        AppName: !Ref AppName
        ECSClusterName: !Ref ECSClusterName
        Namespace: !Ref Namespace
        TaskDefinitionArn: !GetAtt __CF_APP_NAME____TYPE__TaskDefStack.Outputs.TaskDefinitionArn
        VpcId: !Ref VpcId
        VpcSubnetIds: !Sub '${PrivateSubnet1},${PrivateSubnet2}'
        SecurityGroupIds: !Ref SecurityGroupId
        ContainerName: !Ref AppName
        ContainerPort: !Ref ContainerPort
        ALBHTTPListenerArn: !Ref ALBHTTPListenerArn
        AppHostHeader: !Ref AppHostHeader
        ListenerRulePriority: !Ref ListenerRulePriority
        DesiredCount: !Ref DesiredCount
        ScalingMinCapacity: !Ref ScalingMinCapacity
        ScalingMaxCapacity: !Ref ScalingMaxCapacity
        CPUScaleOutThreshold: !Ref CPUScaleOutThreshold
        CPUScaleInThreshold: !Ref CPUScaleInThreshold
        MemoryScaleOutThreshold: !Ref MemoryScaleOutThreshold
        MemoryScaleInThreshold: !Ref MemoryScaleInThreshold
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-service'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
          