name: CD - Deploy to dev

on:
  push:
    branches: [qa-i]
    paths:
      - 'api-config.json'
      - 'ui-config.json'
      
permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    uses: rpx/github_shared_templates/.github/workflows/cd-workflow.yaml@main
    with:
      environment: "qa"
      stacks-path: "iac/aws/us-east-1"
      app-name:    "sample-service"      